### ISSUE TITLE
HELO ADMIN dll not fouind

### ISSUE THREAD

**Issue by GlutenFreeVapes** [occ-ai/obs-squawk#1]
19:26:57.408: LoadLibrary failed for '../../obs-plugins/64bit/obs-squawk.dll': The specified module could not be found.

**Comment by royshil** [comment]
@GlutenFreeVapes the latest download should fix this https://github.com/occ-ai/obs-squawk/releases/tag/0.0.1
published a couple minutes ago

**Comment by GlutenFreeVapes** [comment]
Okay thanks admin.
It works now! Plays sounds pretty darn good!!!!

However the sound playback has craclking in it (tried using 44.1khz, changing voicemeeter sample rates etc.

Speed is quite impressive, considering it's using the CPU!
However longer than 1 sentence take notably long, perhaps it's possible to have GPU acceleration in the future?
